# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
# 项目路径含中文，绕过非 ASCII 路径检查
android.overridePathCheck=true
kotlin.code.style=official
# React Native 0.75 需要
newArchEnabled=false
hermesEnabled=true
# 禁用自动下载 JDK toolchain，但允许检测本地 JDK
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
